### ISSUE TITLE
[Enhancement]: Afficher le fait qu’on note soit ramener sur 20

### ISSUE THREAD

**Issue by Ahhj93** [PapillonApp/papillon-v5#106]
### Description du problème

Une note ramenée sur 20 ne vaut pas la même choisi que si elle ne l’est pas.

### Description de l'amélioration

Ajouter une petite ligne pour indiquer le fait qu’une note soit ramenée sur 20

**Comment by LeGeek01** [comment]
bonjour, si je comprend bien tu veux que lors-ce qu'une note est ramenée sur 20 il y ai une ligne dans l'affichage des notes pour l'indiquer ?

**Comment by tom-theret** [comment]
![image](https://user-images.githubusercontent.com/33373907/233354549-bfb555c8-5007-46c9-8d3e-0176dd7cffc3.png)

Il y a déjà ça !

**Comment by Ahhj93** [comment]
Je voulais dire sur une note ramenée sur 20 sur Pronote.![image](https://user-images.githubusercontent.com/69793084/233552121-484a75b1-ddf9-4db6-aaa3-d622bbb5f026.jpeg)

**Comment by lucas-luchack** [comment]
Normalement Vincent l'a déjà ajouté. Je lui avais fait remonter le fait que l'on ne voyait pas cette information. Je me renseigne sur l'implémentation de ce dernier.
