### ISSUE TITLE
Weekend

### ISSUE THREAD

**Issue by TheTiger72** [PapillonApp/papillon-v5#25]
### Description du problème

Ont vois le samedi et le dimanche dans le calendrier même si ont a pas de cours ces jours là

### Description de l'amélioration

Un bouton dans les paramètres pour désactiver l’affichage du samedi et du dimanche du calendrier.

**Comment by lucas-luchack** [comment]
Nous ne mettrons pas en place cette suggestion.
En effet, nous aller implémenter ce qui est dis dans la #26 mais nous ne cacherons pas le weekend car ce dernier peut être utile pour certains pour par exemple ajouter des cours personnalisées.

**Comment by TheTiger72** [comment]
Je comprends, mais ce que je voulais dire c'est de faire un bouton on/off pour désactiver ou activer l'affichage du week end, donc cela laisserait la possibilité à l'utilisateur de laisser ou non le week-end et que si le week-end est désactivé et qu'un cours est ajouté (par exemple le samedi) que le calendrier affiche simplement le jours avec le cours personnalisé.

**Comment by moeenio** [comment]
Ou alors, masquer automatiquement les jours ou l'on n'a aucun cours?

**Comment by lucas-luchack** [comment]
Nous ne mettrons pas ce paramètre non plus, même raison qu'au dessus...
De plus, on ne peux pas désactiver **l'affichage** de certains jours.

**Comment by moeenio** [comment]
> même raison qu'au dessus

Cours personnalisés?
