### ISSUE TITLE
[Enhancement]: Paramètre pour utiliser un serveur d'API personnalisé

### ISSUE THREAD

**Issue by moeenio** [PapillonApp/papillon-v5#29]
### Description du problème

Pour utiliser cette application il faut actuellement accepter de faire confiance au pelo qui héberge le serveur de l'API, ou si l'on utilise son propre serveur, modifier l'URL du serveur dans le code de l'application.

### Description de l'amélioration

Il pourrait être intéressant de pouvoir chosir le serveur API à utiliser depuis l'interface de l'application, cela préférablement avant la connexion.

**Comment by andronedev** [comment]
Cette fonctionnalité a déjà été implémenté dans la version en cours de développement, elle sera disponible très prochainement dans la version béta public 😉

L'équipe papillon 🦋
