### ISSUE TITLE
Barre de défilement bugé

### ISSUE THREAD

**Issue by TheTiger72** [PapillonApp/papillon-v5#32]
### Description du bug

La barre de défilement s’affiche en plein milieu du menu vie scolaire

### Etapes à reproduire

1. Aller dans le menu vie scolaire
2. Défilé

### Comportement attendu

Ne pas voir la barre de défilement, ou qu’elle soit placé à droite

### Appareil

iPhone 13

### OS

iOS 16.3 beta 3 dev RC

### Version

5.0.15 sur TestFlight

### Environnement

Application iOS

### Captures d'écran / vidéo

![B49D5A78-3D5C-43AB-AF5D-981AD6BB3E11](https://user-images.githubusercontent.com/84013544/217069644-2fc257c8-607f-439a-a77c-44ab95cd27bc.jpeg)

**Comment by lucas-luchack** [comment]
Non reproductible de mon côté...
Voyons avec @ecnivtwelve

**Comment by TheTiger72** [comment]
Faut avoir assez d'absence pour défilé je pense

**Comment by lucas-luchack** [comment]
J'ai testé avec plein d'absence bien sûr

**Comment by TheTiger72** [comment]
Que sur iPhone peux-être ?

**Comment by lucas-luchack** [comment]
Le problème a été trouvé et normalement fixé.

Il faut maintenant attendre la prochaine mise à jour !
