### ISSUE TITLE
Design du modal des Notes

### ISSUE THREAD

**Issue by lucas-luchack** [PapillonApp/papillon-v5#33]
### Description du problème

Les deux modals des notes : matière et note individuelle, n'ont pas les mêmes icônes et le même design (header).

### Description de l'amélioration

En attendant le rework complet du modal (*prévu*) unifier ces derniers pour plus de cohérence.

### Contexte supplémentaire

Modal d'une matière :
![image](https://user-images.githubusercontent.com/39491773/217307219-d50b8eb2-eb85-428d-9f1e-0ee501afa853.png)

Modal d'une note :
![image](https://user-images.githubusercontent.com/39491773/217307352-18bdfcc1-53fb-41b9-8397-039bf753b0c0.png)

**Comment by lucas-luchack** [comment]
Fixed

**Comment by moeenio** [comment]
quel commit
