### ISSUE TITLE
Mettre l'application sous licence libre

### ISSUE THREAD

**Issue by moeenio** [PapillonApp/papillon-v5#35]
### Description du problème

Aussi libre que l'application soit censé être, en pratique il n'y a pas de licence l'indiquant donc pour le moment tous les droits sont réservés.

### Description de l'amélioration

Mettre l'application explicitement sous une licence libre/open source. Voir https://choosealicense.com/

**Comment by lucas-luchack** [comment]
Déjà sous licence
