### ISSUE TITLE
Changement des notes selon trimestre

### ISSUE THREAD

**Issue by BloomyInDev** [PapillonApp/papillon-v5#37]
### Description du bug

Les notes ne changent pas quand on change de trimestre

### Etapes à reproduire

1. Aller dans la partie notes
2. Mettre le trimestre 2
3. Passer au trimestre 1
4. Voir que les notes n'ont pas changé

### Comportement attendu

Les notes s'actualisent pour changer

### Appareil

Samsung S10e

### OS

Android 12 / OneUI 4.1

### Version

5.0.15

### Environnement

Application Android

**Comment by TheTiger72** [comment]
Aucun problème de mon côté 
iPhone 13 iOS 16.3 RC
Papillon 5.0.15

**Comment by tom-theret** [comment]
~~J'ai eu aussi le problème sur :
iPhone 13 mini 16.3 stable
Papillon 5.0.14~~
**Pas révélant** *(modifié par un membre de l'org)*

**Comment by BloomyInDev** [comment]
J'ai trouvé que sa le faitt que la première fois qu'on change de trimestre et que le haut de la page montre aucunn trimestre

**Comment by LeGeek01** [comment]
c'est normalement fixé avec ma pull request (l'issue peut être fermée @lucas-luchack)

**Comment by moeenio** [comment]
non puisque la pr n'est pas encore merged

**Comment by BloomyInDev** [comment]
G plus le bug depuis quelques temps (g pas fait extrêmement gaffe à la ver ou sa a arrêté de bug)
