### ISSUE TITLE
Widget/Live Activities iOS

### ISSUE THREAD

**Issue by TheTiger72** [PapillonApp/papillon-v5#40]
### Description du problème

Widgets et Live Activities iOS 16

### Description de l'amélioration

Bonjour, mon idée serait d’avoir des widgets en 1x1 2x1 et 3x3 pour voir les devoirs/notes/emploi du temps
Je propose aussi de rajouter des widgets pour l’écran verrouillé iOS avec par exemple le prochain cours avec la salle ou la dernière note, ou la matière et la date d’un devoir à rendre.
Et si possible ça serait bien d’ajouter des lives activities sur l’écran verrouillé pour par exemple afficher le temps restant d’un cours.

**Comment by BloomyInDev** [comment]
Chais pas si sa rentre ici mais si c'est fait sur ios, est ce que sa peut être fait pour android ?

**Comment by TheTiger72** [comment]
> Chais pas si sa rentre ici mais si c'est fait sur ios, est ce que sa peut être fait pour android ?

Je crois qu'il y'a des widgets aussi sur Android donc oui
