### ISSUE TITLE
[Enhancement]: Pouvoir cliquer sur les devoirs dans le menu d'acceuil

### ISSUE THREAD

**Issue by Nijigokoro** [PapillonApp/papillon-v5#43]
### Description du problème

Quand on va sur l'écran d'accueil, on doit swipe à droite et aller dans "Travail à faire" pour afficher l'entièreté du contenu d'un devoir qui est pourtant sur l'écran d'acceuil

### Description de l'amélioration

Pouvoir cliquer sur un devoir dans l'écran d'accueil pour faire apparaitre l'entièreté de son contenu

### Contexte supplémentaire

![image](https://user-images.githubusercontent.com/92746684/223465411-8a4b2b9c-985a-4b87-b764-e2221a5e0f3b.png)

**Comment by ecnivtwelve** [comment]
C'est maintenant possible ! https://github.com/PapillonApp/Papillon/commit/eaf04918420a06e6deb0fab6bfdc01f77a9c5f4b
