### ISSUE TITLE
[Enhancement]: Option pour changer le nom des matières

### ISSUE THREAD

**Issue by miorapkmn** [PapillonApp/papillon-v5#60]
### Description du problème

Dans beaucoup d'établissements scolaires (dont le mien), le nom est matières et en majuscule (par exemple "FRANCAIS") ou encore raccourci (par exemple "NUMERIQUE SC.INFORM."), et je trouve ça très déplaisant personnellement (ça donne un peu l'impression qu'on nous crie dessus).

### Description de l'amélioration

Une option dans les paramètres (potentiellement dans "Personnaliser Papillon") qui affiche toutes les matières auxquelles on assiste avec la possibilité de changer le nom (et pourquoi pas aussi la couleur) de cette matière.

**Comment by moeenio** [comment]
Il faut noter que pronote ne fournit pas d'ID constant entre chaque session pour une même information.

**Comment by miorapkmn** [comment]
Il devrait quand même être possible de faire quelque chose simplement en remplaçant le nom d'une matière (par exemple "MATHEMATIQUES") par un autre (par exemple "Maths")

**Comment by lucas-luchack** [comment]
Cela n'est pas prévu pour le moment et ne sera sûrement jamais mis en place...
De plus l'utilité de cette modification est très limité voir totalement inutile.
