### ISSUE TITLE
Retour haptic

### ISSUE THREAD

**Issue by TheTiger72** [PapillonApp/papillon-v5#61]
### Description du problème

Un bouton dans les paramètres pour activé le retour haptic sur les paramètres

### Description de l'amélioration

![IMG_2884](https://user-images.githubusercontent.com/84013544/225896680-93596689-f5a4-46f2-a9f2-6ad9cba38fcb.jpeg)

**Comment by lucas-luchack** [comment]
C'est à dire ?
Un retour haptic lors de l'appui sur un switch des paramètres ?

**Comment by TheTiger72** [comment]
Oui c'est ça, je trouve ça plus "agréable" quand il y a un retour haptic

**Comment by ecnivtwelve** [comment]
je pensais qu'il y en avait déja un mais non
ajouté ici -> https://github.com/PapillonApp/Papillon/commit/c254237241d5ac612235baea4f4029043712441b
