### ISSUE TITLE
[Enhancement]: Rajouter des devoirs manuellement

### ISSUE THREAD

**Issue by sivelswhy** [PapillonApp/papillon-v5#80]
### Description du problème

Le problème que certains professeurs ne mettent pas les devoirs sur Pronote

### Description de l'amélioration

Parfois, des professeurs ne mettent pas les devoirs sur pronote ce qui est un peu chiant. Je propose donc de pouvoir rajouter manuellement des devoirs, similairement aux cours custom

**Comment by TheTiger72** [comment]
Je trouve l'idée génial, car personnellement au lycée les professeurs mettent les devoirs que sur it's learning et jamais sur Pronote qui est pourtant plus facile d'accès et plus facile à voir
Le fait de pouvoir mettre des devoirs personnalisées serait bien pour s'organiser et coché quand ils sont fait 👍

**Comment by lucas-luchack** [comment]
Déjà prévu !
Mais merci de montrer votre attente pour cette fonctionnalité ! 😉

**Comment by moeenio** [comment]
> Déjà prévu !

C'est mieux de considérer que c'est pas officiellement "prévu" tant que c'est pas indiqué publiquement \:)

**Comment by lucas-luchack** [comment]
> > Déjà prévu !
> 
> C'est mieux de considérer que c'est pas officiellement "prévu" tant que c'est pas indiqué publiquement :)

Non c'est officiellement prévu même si ce n'est pas indiqué explicitement comme plein d'autres fonctionnalités

**Comment by moeenio** [comment]
> Non c'est officiellement prévu même si ce n'est pas indiqué explicitement comme plein d'autres fonctionnalités

Bah publiez-les si vous voulez qu'on ait des trucs à contribuer lol

**Comment by moeenio** [comment]
> ce n'est pas indiqué explicitement comme plein d'autres fonctionnalités

Pourquoi ne pas les indiquer explicitement?

**Comment by ecnivtwelve** [comment]
Ajouté dans https://github.com/PapillonApp/Papillon/commit/d6ba4365d8976838e5b5e3c3caa3da6c012d619c
