### ISSUE TITLE
Rajouter les messages de reconnexion

### ISSUE THREAD

**Issue by LeGeek01** [PapillonApp/papillon-v5#83]
### Description du problème

Je ne trouve pas utilise de supprimer les messages de reconnexion comme Vincent vient de le faire. Cela permet une information sur l'état de la connexion des serveurs, et peut expliquer à l'utilisateur pourquoi la requête prend du temps à être traitée.

### Description de l'amélioration

Remettre donc les messages comme ils étaient au départ.

**Comment by ecnivtwelve** [comment]
Je les ai supprimé car effectivement ils indiquent l'état de connexion à l'utilisateur, mais cela au prix d'une notification assez perturbante et récurrente. En attendant de trouver une meilleure alternative, je préfère remplacer ces notifications par des messages d'erreur ou de chargement prolongé dans les onglets directement pour conserver une UX correcte sur les chargements sans pour autant constamment déranger l'utilisateur
